name: Pr

on:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Asdf
        uses: ./.github/actions/setup-tooling
        with:
          SetupCommand: ./tools.sh

      - name: Install Node Modules
        uses: ./.github/actions/setup-yarn

      - name: lint
        run: just lint

      - name: unit test
        run: just unittest

      - name: build
        run: just build

      - name: integration test
        run: just integrationtest

      - name: docs
        run: just docs
